version: "2"
services:
  app:
    restart: always
    build: .
    expose:
      - "8000"
    container_name: "app"
    image: app_image
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    networks:
      - network1
    volumes:
      - ./:/app
      - ./data:/app/data
      - static_volume:/app/static
      - ./logs:/app/logs
    entrypoint: ["sh", "/app/docker-entrypoint.sh"]
    env_file:
      - .env
    logging:
      options:
        max-size: "100m"
        max-file: "3"
  redis:
    restart: always
    hostname: redis
    container_name: "redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - network1
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  postgres:
    image: postgres:11
    container_name: "postgres"
    restart: on-failure
    environment:
      - POSTGRES_DB=propublica_ccrb_allegations
      - POSTGRES_USER=propublica_ccrb_allegations
    networks:
      - network1
    volumes:
      - propublica_ccrb_allegations_api:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      options:
        max-size: "100m"
        max-file: "3"
volumes:
  propublica_ccrb_allegations_api:
  redis_data:
  static_volume:
networks:
  network1:
